### ISSUE TITLE
meteor crashes on running due to syntax error in SRL module

### ISSUE THREAD

**Issue by AdamJacobson** [corsonknowles/RegExTranslator.com#4]
// In local file
import SRL from 'srl';

// in console
=> Started proxy.
=> Started MongoDB.
W20170805-15:49:41.738(-7)? (STDERR) /Users/Adam/aa/RegExTranslator.com/node_modules/srl/lib/Builder.js:163
W20170805-15:49:41.780(-7)? (STDERR)     digit(min = 0, max = 9) {
W20170805-15:49:41.780(-7)? (STDERR)               ^
W20170805-15:49:41.781(-7)? (STDERR)
W20170805-15:49:41.782(-7)? (STDERR) SyntaxError: Unexpected token =
W20170805-15:49:41.783(-7)? (STDERR)     at exports.runInThisContext (vm.js:53:16)
W20170805-15:49:41.783(-7)? (STDERR)     at Module._compile (module.js:373:25)
W20170805-15:49:41.783(-7)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170805-15:49:41.784(-7)? (STDERR)     at Module.load (module.js:343:32)
W20170805-15:49:41.784(-7)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170805-15:49:41.785(-7)? (STDERR)     at Module.require (module.js:353:17)
W20170805-15:49:41.785(-7)? (STDERR)     at require (internal/module.js:12:17)
W20170805-15:49:41.786(-7)? (STDERR)     at Object.<anonymous> (/Users/Adam/aa/RegExTranslator.com/node_modules/srl/lib/SRL.js:3:17)
W20170805-15:49:41.787(-7)? (STDERR)     at Module._compile (module.js:409:26)
W20170805-15:49:41.787(-7)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)

**Comment by AdamJacobson** [comment]
Unable to find fix. Workaround is add the node module folder for SRL into the local file structure and reference functions that way.

Horrible, horrible workaround.

**Comment by AdamJacobson** [comment]
Apparently, this issue only happens on the server side. So, if used on the client side there is no issue.
